### ISSUE TITLE
transparentTarget not working

### ISSUE THREAD

**Issue by witalobenicio** [prscX/react-native-app-tour#47] opened 2018-09-25 21:30 UTC
I'm using transparentTarget to show my view above the circle and isn't working.

**Comment by witalobenicio** [comment] 2018-09-26 13:29
@prscX I've tested now in iOS and works just like expected, but in Android version isn't working.

iOS:
<img width="373" alt="captura de tela 2018-09-26 as 10 26 51" src="https://user-images.githubusercontent.com/4964291/46082963-b8786600-c176-11e8-81e6-6da3fab5d47d.png">

Android:
![screenshot_20180926-102745](https://user-images.githubusercontent.com/4964291/46083078-f70e2080-c176-11e8-9dc6-681cb58452a3.png)

**Comment by witalobenicio** [comment] 2018-09-27 13:45
@prscX I don't know if it helps but when I've used in a native android app, the version of lib that I used was `1.6.0`

**Comment by witalobenicio** [comment] 2018-09-28 22:21
@prscX any updates?

**Comment by prscX** [comment] 2018-10-01 06:50
Thanks @witalobenicio for raising the issue.

Have you specified `transparentTarget = false`? Unlike iOS it is not supported on Android. By default `transparentTarget` on Android is `true`. On Android, it will show background content with transparent circle.

Please let me know incase it still does not works.

Thanks
</ Pranav >

**Comment by witalobenicio** [comment] 2018-10-01 12:25
@prscX Yes...if specified `transparentTarget = false` on Android. I've seen that the default value on Android is true, and I've set to false.
The problem is that the view is been draw below the target view (as shown in the screenshot).
I used the android lib before in a native project, and works like expected (view above targetview).

**Comment by prscX** [comment] 2018-10-01 13:56
@witalobenicio: Previous I also wanted to achieve the same iOS behavior on Android, but I was not able to achieve the same. I thought it was not supported by native library. Since you have specified that it works, I will give it a another try.

Will keep you posted.

Thanks
</ Pranav >

**Comment by witalobenicio** [comment] 2018-10-01 14:24
@prscX Thank's man. I know in native library works (you can see an example of this working at: https://play.google.com/store/apps/details?id=br.com.isilist.android).

I hope we can use the same feature with your lib. 😄

**Comment by witalobenicio** [comment] 2018-10-05 14:51
Hi @prscX any updates?

**Comment by prscX** [comment] 2018-10-07 08:42
Hi @witalobenicio: I have done a detailed analysis and figured out the root cause of the issues.

Basically [KeepSafe/TapTargetView](https://github.com/KeepSafe/TapTargetView) provides multiple API in order to show a tour on a specific target.

* **TapTarget.forView**
* **TapTarget.forBounds**

We are using **TapTarget.forBounds** API in order to render Tour view for a specific view. Since the views from created and rendered by React, we can't use **TapTarget.forView** API, we have to use **TapTarget.forBounds** API only.

This can't be fixed in the library as of now. I would recommend to use transparent target only. 

Thanks
</ Pranav >

**Closed as completed by prscX** 2018-10-07 08:42 UTC

**Comment by witalobenicio** [comment] 2018-10-08 12:36
@prscX Thanks for the explanation. I'll try to use with transparent target...for my purpose I don't think it will fit, but I'll give a try.
I'll try to dig up the native lib and try to find an alternative too. If I can found it I'll let you know.

**Comment by witalobenicio** [comment] 2018-10-08 19:12
@prscX this PR #49 will enable `transparentTarget = false` and fix possible crashes due to views that are not rendered anymore after added to apptourtargets.

**Comment by danieljgp2** [comment] 2019-08-30 19:15
@witalobenicio im having some problems on android as you can see here https://github.com/prscX/react-native-app-tour/issues/78

it seems to be related with your issue, how can i access to your fork to test it on my app ?
